# @package _global_
train:
  # Mode-specific setting
  sync: false  # Force asynchronous mode
  
  # Shared training settings
  mixed_precision: true
  epochs: 1
  steps_per_batch: 16
  buffer_size: 32
  total_dialog_turns: 100_000
  optim_batch_size: 4
  gradient_accumulation_steps: 4
  kl_coef_in_loss: false 
